function Im0011 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IM0011 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  IM0011 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Im0011 = importfile("C:\Users\angel\Downloads\ALL-IDBv2\WBC_label\ALL-IDB1\original\Im001_1.xyc", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Feb-2023 16:46:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Im0011 = readtable(filename, opts);

end